# Inner Products and Norms of Vectors

- #### Hands-on Experiential Learning <font color="red">for the Software Engineer</font>


![](img/QC_Math_Banner.png "")

<font color="red">**Notice**</font>: All materials herein were <font color="red">**curated**</font> by **Matthew R. Versaggi (profversaggi@gmail.com)** and are released into the open source to foster growth and welfare of expanding the Quantum Computing domain - the only obligation one incurs when using, copying, distributing or referencing this is to kindly reference the author and send me an email so I know how useful the material is to you.

#### <font color="red">Recommendations</font>: 

> **<font color="blue">It's highly recommended to take structured QC Math courses <font color="red">like</font>:</font>**
> #### Math Prerequisites for Quantum Computing
> - https://www.udemy.com/course/mathematics-prerequisites-for-quantum-computing-and-quantum-physics/

> #### Advanced Math for Quantum Computing
> - https://www.udemy.com/course/qc201-advanced-math-for-quantum-computing-mathematics-physics/



#### <font color="red">Materials Inspiration and Author(s)</font>: 

> **<font color="blue">Amelie Schreiber</font>**
- Article: https://towardsdatascience.com/quantum-computing-for-the-newb-5e0737e3ca4
- Course: https://the-singularity-research.github.io/linear_algebra_for_quantum_computing/
- GitHub: https://github.com/The-Singularity-Research/linear_algebra_for_quantum_computing

> **<font color="blue">QWorld</font>**
- Site: https://qworld.lu.lv/
- GitLab: https://gitlab.com/qkitchen/basics-of-quantum-computing

## Importing NumPy

As usual, we will need to import NumPy

In [2]:
import numpy as np

## Introduction


### <font color="red">**Background Information**</font>: 

- **Interactive graphical Inner-Product of vectors**: - https://elsenaju.eu/Determinant/Inner-product.htm

- **DOT (INNER) PRODUCT CALCULATOR**: - https://www.emathhelp.net/calculators/linear-algebra/dot-inner-product-calculator/

- **Immersive Linear Algebra**: - http://immersivemath.com/ila/index.html

<BR>

### <font color="red">**Why this is important**</font>: 

#### The most important vectors we will encounter will be $2$-dimensional complex vector which are of length $1$. 


In this section we will define the <font color="red">**inner product**</font> of two vectors, and the <font color="red">**norm**</font> (**length**) of a vector which is derived from the **inner product of the vector with itself**. 

- The vectors of length $1$ are sometimes referred to as **unit vectors**. We will discuss **complex unit vectors** in <font color="blue">$2$-dimensional space $\mathbb{C}^2$ </font>and how they relate to **qubits**. This will then lead to a discussion of the **Bloch sphere** which will be a useful way of *understanding qubits and how quantum gates act on them*. 


### <font color="blue">Inner Products</font>
**Inner Products** are a more *general case* of the **dot-product**, but *for most of our purposes, they can be thought of as the same thing*. 

> The **most basic case of an inner product** and the one we will use the most often can be thought of as the **product of a <font color="red">row</font> vector and a <font color="red">column</font> vector of the <font color="blue">same dimension</font>**:

\begin{align} \langle A| = \begin{pmatrix}
a_1, & a_2, & \cdots, & a_n
\end{pmatrix}, \quad \quad
|B\rangle = \begin{pmatrix}
b_1 \\ b_2 \\ \vdots \\ b_n
\end{pmatrix} \end{align}

Taking the <font color="blue">**inner product**</font> of $\langle A|$ and $|B\rangle$ gives the following:

<font color="blue"> 

\begin{align} \langle A| B \rangle &= \begin{pmatrix} 
a_1, & a_2, & \cdots, & a_n
\end{pmatrix}
\begin{pmatrix}
b_1 \\ b_2 \\ \vdots \\ b_n
\end{pmatrix}\\
&= 
a_1b_1 + a_2b_2 + \cdots + a_nb_n\\
&= \sum_{i=1}^n a_ib_i
\end{align}

</font>


<BR>

**As a basic example**, take the inner product of the following $2$-dimensional vectors, 


\begin{align} \langle A| = \begin{pmatrix}
3i, & 2
\end{pmatrix}, \quad \quad |B\rangle = \begin{pmatrix}
5+2i \\ 1-i
\end{pmatrix} \end{align}

#### as follows:

<font color="blue"> 
    
\begin{align}
\langle A| B \rangle = \begin{pmatrix}
3i, & 2
\end{pmatrix}
\begin{pmatrix}
5+2i \\ 1-i
\end{pmatrix} &= 
3i(5+2i) + 2(1-i)\\ 
&= 15i-6+2-2i\\ 
&= -4+13i
\end{align}

</font>

<BR>

In order to define a <font color="red">**complex vector**</font> so that we can take its **conjugate transpose**, also called the **Hermitian conjugate**, we must define it as a <font color="red">**matrix**</font>. 


So, suppose we have the following **column vector (ket-vector)**:

\begin{align}
|A\rangle = \begin{pmatrix} 1-i \\ 3 \\ 2i \\ 5+i \end{pmatrix}
\end{align}

<font color="blue"> Then of course its **Hermitian conjugate** would be the bra-vector:</font>

\begin{align}
\langle A| = \begin{pmatrix}1+i, & 3, & -2i, & 5-i \end{pmatrix}
\end{align}

<BR>

Now, in **Python**, we must remember to use "$j$" instead of $"i"$ for the imaginary unit,  and we must **define** the $4 \times 1$-matrix:

#### Define the 4x1 <font color="red">matrix</font> version of a <font color="red">column</font> vector (instead of using the np.<font color="red">array</font>() version):

In [2]:
# Define the 4x1 matrix version of a column vector (instead of using the np.array() version):

A = np.matrix([[1-1j], 
               [3], 
               [2j], 
               [5+1j]])

print(A)

[[1.-1.j]
 [3.+0.j]
 [0.+2.j]
 [5.+1.j]]


In [3]:
type(A)

numpy.matrix

#### Compute the Hermitian Conjugate  (also called the <font color="red">Complex conjugate</font>):

In [4]:
# Compute the Hermitian Conjugate:
A.H

matrix([[1.+1.j, 3.-0.j, 0.-2.j, 5.-1.j]])

#### Compute the <font color="red">inner product</font> $ \langle A|A \rangle $ 
- Simply **multiply** the two matrix versions just computed using Numpy's **DotProduct** FN:

In [5]:
np.dot(A.H, A)

matrix([[41.+0.j]])

Let's define **another $4$-dimensional complex <font color="red">row</font> vector**  <font color="blue">$\langle B|$</font>:

\begin{align}
\langle B| = \begin{pmatrix}
-3i, & 2+2i, & -6i, & -7
\end{pmatrix}
\end{align}

Once we have defined this **bra-vector**, let's compute the following **inner products**:
<BR><BR>

\begin{align}
\langle B|A \rangle, \quad \langle B|B \rangle, \quad \langle A|B \rangle.
\end{align}

<BR><BR>

### Define B as a 1x4 matrix

In [6]:
# Define B as a 1x4 matrix

B = np.matrix([[-3j, 2+2j, -6j, -7]])

print(B)

[[-0.-3.j  2.+2.j -0.-6.j -7.+0.j]]


#### Check shape

In [7]:
B.shape

(1, 4)

#### #Compute the <font color="red"> Hermitian Conjugate</font> (also called the Conjugate Transpose) of B, which is a <font color="blue">ket-vector</font>

In [9]:
#Compute the Hermitian Conjugate of B, which is a ket-vector

B.H

matrix([[-0.+3.j],
        [ 2.-2.j],
        [-0.+6.j],
        [-7.-0.j]])

### <B|A>

In [10]:
# Compute <B|A>

np.dot(B,A)

matrix([[-20.-4.j]])

### <B|B>

In [11]:
# Compute <B|B>

np.dot(B, B.H)

matrix([[102.+0.j]])

### <A|B>

In [13]:
# Compute <A|B>

np.dot(A.H, B.H)

matrix([[-20.+4.j]])

#### Outer Product

There is a different kind of product on two vectors which we will cover later called the **[outer product](https://en.wikipedia.org/wiki/Outer_product)**. 


> The outer product is a specific case of the tensor product and is written in this case by $ |A\rangle \langle A|$. It is important to make this distinction now and note that the two **are not the same**. 


- The **inner product** always yields a **<font color="red">number</font>**, which can be complex valued if the two vectors are complex valued. 
- The **outer product** in general gives a **<font color="red">matrix</font>**. 

#### outer product in general gives a matrix

In [14]:
np.dot(A, A.H)

matrix([[ 2. +0.j,  3. -3.j, -2. -2.j,  4. -6.j],
        [ 3. +3.j,  9. +0.j,  0. -6.j, 15. -3.j],
        [-2. +2.j,  0. +6.j,  4. +0.j,  2.+10.j],
        [ 4. +6.j, 15. +3.j,  2.-10.j, 26. +0.j]])

For the more adventurous readers who understand how to multiply matrices, and to prepare for future computations where matrices are involved, we will compute a more **general "inner product"**. 


> If this does not make any sense to you and matrix multiplication is a foreign concept, we will discuss matrix multiplication in this chapter as a refresher, but now might be a good time to refresh your memory on how to multiply matrices if it is unfamiliar. 

When we discuss <font color="red">**measurements**</font> and <font color="red">**expectation values**</font>  we will need to consider the case when there is a matrix in between the **bra-** and **ket-** vector. 

> Take for example the **Pauli-Z matrix**, which we will discuss more later on:

<font color="blue"> 
    
\begin{align} Z = \begin{pmatrix}
1 & 0 \\
0 & -1
\end{pmatrix} \end{align}

</font>

Now take the following **bra-vector** and **ket-vector**:


\begin{align} \langle A| = \begin{pmatrix}
i/\sqrt{2}, & -i/\sqrt{2}
\end{pmatrix}, \quad \quad |A\rangle = \begin{pmatrix}
-i/\sqrt{2} \\ i/\sqrt{2}
\end{pmatrix} \end{align}

<BR>

### Now, we can compute the following variation on the inner product

\begin{align}
\langle A| Z |A \rangle &= 
\begin{pmatrix}
i/\sqrt{2}, & -i/\sqrt{2}
\end{pmatrix}
\begin{pmatrix}
1 & 0 \\
0 & -1
\end{pmatrix}
\begin{pmatrix}
-i/\sqrt{2} \\ i/\sqrt{2}
\end{pmatrix} \\
&= \begin{pmatrix}
i/\sqrt{2}, & -i/\sqrt{2}
\end{pmatrix}
\begin{pmatrix}
-i/\sqrt{2} \\ -i/\sqrt{2}
\end{pmatrix} \\
&= 1/2 - 1/2 \\
&= 0
\end{align}

We will encounter such calculations many more times when we discuss **measurements** and **expectations**. 


> *If this is a little confusing, it is not important to worry too much about it just yet.*  **Matrix multiplication** will be covered shortly, and later we will discuss **measurements** and **expectation** values, at which point we should be comfortable computing more general version of the **"inner product"**.

<BR>

# <font color="red">Graded Exercises</font>  for use <font color="blue">with structured courses.</font>

## Inner Products

#### <font color="blue">*This work will take some time, so block off enough time to adequately cover it*</font>. 


- Go through the **entire** JNB and complete each of the exercises, including any supplementary Video's - hand in completed <font color="red">**PDF**</font> from this JNB once finished.


- Step through the code for **each** of the above exercises, make sure you can (1) execute it, and (2) know what it does.


- <font color="blue">Complete Challenge Exercises below.</font> **(turn in the JNB)**

#### Write Python code to compute the inner product of: 
    
<BR>    
    
$\begin{pmatrix}
2, & 3i
\end{pmatrix}
\begin{pmatrix}
1+i \\ 4
\end{pmatrix}$ 
    
    
<BR>    

In [9]:
A = np.matrix([[2, 3j]])

print(A)

[[2.+0.j 0.+3.j]]


In [10]:
A.shape

(1, 2)

In [11]:
B = np.matrix([[1+1j], 
               [4]])

print(B)

[[1.+1.j]
 [4.+0.j]]


In [12]:
B.shape

(2, 1)

In [13]:
np.dot(A, B)

matrix([[2.+14.j]])

#### Write Python code to compute the inner product of: 

<BR>
    
$ \begin{pmatrix}
3i, & 1+2i, & 4, & 2i
\end{pmatrix}
\begin{pmatrix}
5 \\ 1-2i \\ -3 \\ -i/2
\end{pmatrix} $

<BR>

In [18]:
A = np.matrix([[3j, 1+2j, 4, 2j]])

print(A)

[[0.+3.j 1.+2.j 4.+0.j 0.+2.j]]


In [19]:
B = np.matrix([[5],
               [1-2j], 
               [-3],
               [-1j/2]])

print(B)

[[ 5.+0.j ]
 [ 1.-2.j ]
 [-3.+0.j ]
 [-0.-0.5j]]


In [20]:
np.dot(A, B)

matrix([[-6.+15.j]])

#### <font color="red">Optional</font>: Write the Python code to compute the following more general "inner product":

<BR>

\begin{align}
\begin{pmatrix}1/\sqrt{2}, & -1/\sqrt{2} \end{pmatrix}
\begin{pmatrix} 1&0\\0&-1 \end{pmatrix}
\begin{pmatrix}1/\sqrt{2}\\ -1/\sqrt{2} \end{pmatrix}
\end{align}

<BR>

In [48]:
import math
A_bra = np.matrix([[1/math.sqrt(2), -1/math.sqrt(2)]])

print(A_bra)

[[ 0.70710678 -0.70710678]]


In [49]:
Z= np.matrix([[1, 0],
            [0, -1]])

print(Z)

[[ 1  0]
 [ 0 -1]]


In [53]:
A.H
print(A.H)

[[ 0.70710678]
 [-0.70710678]]


In [54]:
A_ket = np.matrix([[-1/math.sqrt(2)], 
                   [1/math.sqrt(2)]])

print(A_ket)

[[-0.70710678]
 [ 0.70710678]]


In [55]:
A1=np.dot(Z, A_ket)

In [58]:
np.dot(A_bra, A1)

matrix([[0.]])

![the-end](img/the-end.png "the-end")