# Vectors 
- #### Hands-on Experiential Learning <font color="red">for the Software Engineer</font>


![](img/QC_Math_Banner.png "")

<font color="red">**Notice**</font>: All materials herein were <font color="red">**curated**</font> by **Matthew R. Versaggi (profversaggi@gmail.com)** and are released into the open source to foster growth and welfare of expanding the Quantum Computing domain - the only obligation one incurs when using, copying, distributing or referencing this is to kindly reference the author and send me an email so I know how useful the material is to you.

#### <font color="red">Recommendations</font>: 

> **<font color="blue">It's highly recommended to take structured QC Math courses <font color="red">like</font>:</font>**
> #### Math Prerequisites for Quantum Computing
> - https://www.udemy.com/course/mathematics-prerequisites-for-quantum-computing-and-quantum-physics/

> #### Advanced Math for Quantum Computing
> - https://www.udemy.com/course/qc201-advanced-math-for-quantum-computing-mathematics-physics/



#### <font color="red">Materials Inspiration and Author(s)</font>: 

> **<font color="blue">Amelie Schreiber</font>**
- Article: https://towardsdatascience.com/quantum-computing-for-the-newb-5e0737e3ca4
- Course: https://the-singularity-research.github.io/linear_algebra_for_quantum_computing/
- GitHub: https://github.com/The-Singularity-Research/linear_algebra_for_quantum_computing

> **<font color="blue">QWorld</font>**
- Site: https://qworld.lu.lv/
- GitLab: https://gitlab.com/qkitchen/basics-of-quantum-computing

### Explore Vectors using the Phet Interactive Simulator

In [1]:
from IPython.display import IFrame
IFrame(src='https://phet.colorado.edu/sims/html/vector-addition/latest/vector-addition_en.html', width=900, height=900)

## Introduction

### <font color="red">**Background Information**</font>: 

- **The Physics Classroom - Vectors: Properties and Operations - Complete Toolkit**: 
> - https://www.physicsclassroom.com/Teacher-Toolkits/Vectors/Vectors-Complete-ToolKit
- **Immersive Linear Algebra**: - http://immersivemath.com/ila/index.html


### <font color="red">**Why this is important**</font>: 

**Vectors are fundamental in the study of quantum computing.** The most basic unit of computation in a quantum computer is a **qubit**, which can be represented as a <font color="blue">**$2$-dimensional complex vector of length one**</font>. So understanding vectors will be foundational and necessary for most of the math behind Quantum Computing. 

> Vectors can be thought of in many ways, one of the most basic is simply as an **array of numbers**, which we will often represent as a <font color="red">**column**</font> of numbers called **column vectors**, but in some cases we will also need <font color="red">**row**</font> vectors:


\begin{align} \let\emph\textbf{Column Vector:} \ \begin{pmatrix}
a_1 \\ a_2 \\ \vdots \\ a_n
\end{pmatrix}, \quad \quad \let\emph\textbf{Row Vector:} \ \begin{pmatrix}
a_1, & a_2, & \cdots, & a_n
\end{pmatrix} \end{align}

In [2]:
import numpy as np

## Row Vectors, Column Vectors, and Bra-Ket Notation


> - **VIDEO: Bra Ket Notation | Quantum Mechanics** https://www.youtube.com/watch?v=xdSTZYc8uRg


Create a **column** vector and a **row** vector in Python:

#### Create a ROW Vector

In [3]:
# Create a vector as a Row w/Complex Numbers

row_vector = np.array([2-1j, 7j, -3])

#### Row Vector Shape

In [4]:
row_vector.shape

(3,)

#### Row Vector value

In [5]:
row_vector

array([ 2.-1.j,  0.+7.j, -3.+0.j])

#### Create a COLUMN Vector

In [6]:
# Create a vector as a Row w/Complex Numbers

column_vector = np.array([[2+1j],
                          [-5],
                          [2j]])

#### Column Vector Shape

In [7]:
column_vector.shape

(3, 1)

#### Column Vector value

In [8]:
column_vector

array([[ 2.+1.j],
       [-5.+0.j],
       [ 0.+2.j]])

<font color="red">**Row Vectors**</font> in quantum mechanics are also called <font color="blue">**bra-vectors**</font>, and are denoted as follows:

\begin{align} \langle A| = \begin{pmatrix}
a_1, & a_2, \cdots, & a_n
\end{pmatrix} \end{align}

<font color="red">**Column Vectors**</font> are also called <font color="blue">**ket-vectors**</font> in quantum mechanics denoted as follows:

\begin{align} |B\rangle = \begin{pmatrix}
b_1 \\ b_2 \\ \vdots \\ b_n
\end{pmatrix} \end{align}

In general, if we have a **column vector**, i.e. a **ket-vector**:

\begin{align} |A\rangle = \begin{pmatrix}
a_1 \\ a_2 \\ \vdots \\ a_n
\end{pmatrix} \end{align}

Then the corresponding **bra-vector**:

\begin{align} \langle A| = \begin{pmatrix}
a_1^*, & a_2^*, & \cdots, & a_n^*
\end{pmatrix} \end{align}

is the <font color="red">**complex-conjugate transpose**</font> of the **ket-vector** $|A\rangle$, and *vice-versa*. 

> Remember: 
- The **complex-conjugate** just <font color="blue">**negates**</font> the <font color="red">**imaginary**</font> part of the **complex numbers** 
- The **transpose** of a **row vector is a column vector**, and the transpose of a **column vector is a row vector**.

> **As an example**, if we have the following **ket-vector**:

<font color="blue">

\begin{align} |A\rangle = \begin{pmatrix}
2+i \\ 1-3i
\end{pmatrix} \end{align}

</font>

> then the corresponding **bra-vector** is:

<font color="blue">
    
    
\begin{align} \langle A| = \begin{pmatrix}
2-i, & 1+3i
\end{pmatrix} \end{align}

</font>

> **Reminder**: Computing the **complex conjugates** just <font color="blue">**negates**</font> the <font color="red">**imaginary**</font> part of the **complex numbers**.


The notation $\langle A|$ and $|A\rangle$, for **bra-** and **ket-** vectors respectively, is a reference to **inner products** denoted by brackets and  *will be investigated more in the next section when inner products are defined*. 

<BR>

**As another example**, we might want to have a **pair of $2$-dimensional complex column vectors** (*meaning the entries are complex numbers*):

<BR>
    
<font color="blue">

\begin{align} |A \rangle = \begin{pmatrix}
2-i \\ 5
\end{pmatrix}, \quad \quad
|B \rangle = \begin{pmatrix}
7 \\ 3i
\end{pmatrix} \end{align}

</font>

Remember, <font color="blue">$i^2 = -1$ </font> and so <font color="blue"> $i = \sqrt{-1}$ </font> is <font color="red">imaginary</font> and **complex numbers** are always of the form <font color="red"> $a + bi$ </font>. 

The corresponding **bra-vectors** would then be:

\begin{align} \langle A| = \begin{pmatrix}
2+i, & 5
\end{pmatrix}, \quad \quad \langle B| = \begin{pmatrix}
7, & -3i
\end{pmatrix} \end{align}

**The $2$-dimensional vectors we have listed above** are <font color="red">**not**</font> quite the kind of vectors we will be using most often in quantum computing, but until we introduce the **norm of a vector** and explain what **unit vectors** are, let us **focus on the basic operations we can perform on these vectors**. 




We can always <font color="red">**ADD**</font> two vector of the **same dimension**:

\begin{align} |A\rangle + |B\rangle = \begin{pmatrix}
2-i \\ 5
\end{pmatrix} + \begin{pmatrix}
7 \\ 3i
\end{pmatrix} = 
\begin{pmatrix}
(2-i) + 7 \\ 5 + 3i
\end{pmatrix} = 
\begin{pmatrix}
9-i \\ 5 + 3i
\end{pmatrix} \end{align}

In Python this can be done as follows:

#### Create a pair (A & B) of  2 -dimensional complex COLUMN vectors

In [9]:
# Ket_A:
ket_A = np.array([[2-1j],
                  [5]])

# Ket_B:
ket_B = np.array([[7], 
                  [3j]])

# Print the Addition of the two Kets

print(ket_A + ket_B)

[[9.-1.j]
 [5.+3.j]]


We can multiply **ket-vectors** by <font color="red">**scalars**</font>:

$ 3|A\rangle = 3 \begin{pmatrix} 2-i\\5 \end{pmatrix} = \begin{pmatrix} 6-3i\\15 \end{pmatrix} $

#### Multiply a Ket-Vector by a Scalar

In [10]:
# multiply bra-vectors by scalars:

print(3 * ket_A)

[[ 6.-3.j]
 [15.+0.j]]



We can multiply (**bra-vectors**) by <font color="red">**scalars**</font>:

$ 5\langle B| = 5 \begin{pmatrix} 7, & 3i \end{pmatrix}  = \begin{pmatrix} 35, & 15i \end{pmatrix}$

#### Multiply a Bra-Vector by a Scalar

In [11]:
# multiply ket-vectors by scalars:

bra_B = np.array([[7, 3j]])

print(5 * bra_B)

[[35. +0.j  0.+15.j]]


# <font color="red">Graded Exercises</font>  for use <font color="blue">with structured courses.</font>

## Vectors

#### <font color="blue">*This work will take some time, so block off enough time to adequately cover it*</font>. 


- Go through the **entire** JNB and complete each of the exercises, including any supplementary Video's - hand in completed <font color="red">**PDF**</font> from this JNB once finished.


- Step through the code for **each** of the above exercises, make sure you can (1) execute it, and (2) know what it does.


- <font color="blue">Complete Challenge Exercises below.</font> **(turn in the JNB)**

## Exercises: Vectors
- In Python.


1. Define the following **ket-vector** as an **array** in Python:

\begin{align}
|\psi \rangle = \begin{pmatrix} 2, & 3i \end{pmatrix}
\end{align}

In [15]:
ket_a = np.array([[2], [3j]])
ket_a.shape

(2, 1)

2. Define <font color="blue">$|\psi \rangle$</font> from the **previous problem** (#1) as a **(column) matrix**.
> - Compute its **Conjugate Transpose** (also called the **Hermitian conjugate**). 


In [16]:
np.conj(ket_a)

array([[2.-0.j],
       [0.-3.j]])

3. Define **two ket vectors** (column vectors) [A & B] in <font color="blue">**in Python**</font>.

\begin{align}
|A\rangle = \begin{pmatrix}
2 \\ 5-5j
\end{pmatrix}, \quad
|B\rangle = \begin{pmatrix}
2+3j \\ -3j
\end{pmatrix}
\end{align}

In [17]:
ket_a = np.array([[2], [5-5j]])

ket_b = np.array([[2+3j], [-3j]])

4. Compute $|A\rangle + |B\rangle$


In [18]:
print(ket_a + ket_b)

[[4.+3.j]
 [5.-8.j]]


5. Compute $3|A\rangle$. 

In [19]:
print(3*ket_a)

[[ 6. +0.j]
 [15.-15.j]]


![the-end](img/the-end.png "the-end")