# Tensor Products of Vectors


- #### Hands-on Experiential Learning <font color="red">for the Software Engineer</font>

![](img/QC_Math_Banner.png "")

<font color="red">**Notice**</font>: All materials herein were <font color="red">**curated**</font> by **Matthew R. Versaggi (profversaggi@gmail.com)** and are released into the open source to foster growth and welfare of expanding the Quantum Computing domain - the only obligation one incurs when using, copying, distributing or referencing this is to kindly reference the author and send me an email so I know how useful the material is to you.

#### <font color="red">Recommendations</font>: 

> **<font color="blue">It's highly recommended to take structured QC Math courses <font color="red">like</font>:</font>**
> #### Math Prerequisites for Quantum Computing
> - https://www.udemy.com/course/mathematics-prerequisites-for-quantum-computing-and-quantum-physics/

> #### Advanced Math for Quantum Computing
> - https://www.udemy.com/course/qc201-advanced-math-for-quantum-computing-mathematics-physics/



#### <font color="red">Materials Inspiration and Author(s)</font>: 

> **<font color="blue">Amelie Schreiber</font>**
- Article: https://towardsdatascience.com/quantum-computing-for-the-newb-5e0737e3ca4
- Course: https://the-singularity-research.github.io/linear_algebra_for_quantum_computing/
- GitHub: https://github.com/The-Singularity-Research/linear_algebra_for_quantum_computing

> **<font color="blue">QWorld</font>**
- Site: https://qworld.lu.lv/
- GitLab: https://gitlab.com/qkitchen/basics-of-quantum-computing

## Importing NumPy

We will need to import NumPy for tensor products. 

In [1]:
import numpy as np

### <font color="red">**Why this is important**</font>: 

## Introduction

One of the most common tensor products we will encounter throughout the following chapters of the book will be the <font color="blue">tensor product of two qubits</font>, which are represented by <font color="blue"> $2$-dimensional vector which have length (or "norm")</font> $1$ .

#### The general rule for the tensor product of two $2$-dimensional vectors is as follows:

<BR>
<font color="blue">

\begin{align}
\begin{pmatrix}
a_1 \\ a_2
\end{pmatrix} \otimes
\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} = 
\begin{pmatrix}
a_1 \begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} \\ a_2 \begin{pmatrix}
b_1 \\ b_2
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
a_1b_1 \\ a_1b_2 \\ a_2b_1 \\ a_2b_2
\end{pmatrix}
\end{align}

</font>
<BR>


#### Here is a numerical example:

<BR>
<font color="blue">
    
\begin{align}
\begin{pmatrix}
2 \\ 5
\end{pmatrix} \otimes 
\begin{pmatrix}
3 \\ 1
\end{pmatrix} = 
\begin{pmatrix}
2 \begin{pmatrix}
3 \\ 1
\end{pmatrix} \\ 5 \begin{pmatrix}
3 \\ 1
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
2 \cdot 3 \\ 2 \cdot 1 \\ 5 \cdot 3 \\ 5 \cdot 1
\end{pmatrix} = 
\begin{pmatrix}
6 \\ 2 \\ 15 \\ 5
\end{pmatrix}
\end{align}

</font>
<BR>

For an example using Python we will use the <font color="blue" size=4>**"np.kron()"**</font> function, which is the [Kronecker product](https://en.wikipedia.org/wiki/Kronecker_product), 

> "In mathematics, the **Kronecker Product**, sometimes denoted by <font size=5>**⊗**</font>, is an *operation on two matrices of arbitrary siz resulting in a block matrix*. 

It is a <font color="red">**generalization**</font> of the **outer product** (which is denoted by the same symbol) *from vectors to matrices*, and gives the **matrix of the tensor product with respect to a standard choice of basis**. 

> - The **Kronecker Product** should <font color="red">**not**</font> be confused with the <font color="blue">**usual matrix multiplication**</font>, which is an <font color="red">**entirely different**</font>  operation.

In [2]:
# Define two ket-vectors (A, B) using NP.ARRAY

A = np.array([[2], 
              [5]])

B = np.array([[3],
              [1]])

In [3]:
A

array([[2],
       [5]])

In [21]:
B

array([[3],
       [1]])

In [22]:
# Take the Kronecker (tensor) product of the two column vectors

np.kron(A,B)

array([[ 6],
       [ 2],
       [15],
       [ 5]])

We can also define these two vectors as **<font color="red" size=4>matrices</font>** which will allow us to compute **Hermitian conjugates** (also known as **Conjugate Transpose**). 

The **Kronecker Product** function <font color="blue" size=4>**"np.kron()"**</font> will work all the **same**:

#### Define the ket-vectors as 2x1 <font color="red">**Column Matrices**</font>:

In [4]:
# Define the ket-vectors as 2x1 column matrices, using NP.MATRIX

ket_A = np.matrix([[2], 
                   [5]])


ket_B = np.matrix([[3], 
                   [1]])



In [5]:
ket_A

matrix([[2],
        [5]])

In [6]:
ket_B

matrix([[3],
        [1]])

In [7]:
# Compute their Kronecker product

np.kron(ket_A, ket_B)

matrix([[ 6],
        [ 2],
        [15],
        [ 5]])

#### This can also be done with <font color="red">**Complex Vectors**</font>:

In [8]:
# Define the ket-vectors as 2x1 column matrices:

ket_psi = np.matrix([[2-1j], 
                     [3j]])

ket_phi = np.matrix([[-3], 
                     [4-2j]])

# Compute their Kronecker product

np.kron(ket_psi, ket_phi)

matrix([[-6. +3.j],
        [ 6. -8.j],
        [-0. -9.j],
        [ 6.+12.j]])

Here is a more complicated example with two vectors of different dimensions:

<BR>
<font color="blue">
    
\begin{align}
\begin{pmatrix}
a_1 \\ a_2
\end{pmatrix} \otimes 
\begin{pmatrix}
b_1 \\ b_2 \\ b_3
\end{pmatrix} = 
\begin{pmatrix}
a_1 \begin{pmatrix}
b_1 \\ b_2 \\ b_3
\end{pmatrix} \\
a_2 \begin{pmatrix}
b_1 \\ b_2 \\ b_3
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
a_1b_1 \\ a_1b_2 \\ a_1b_3 \\ a_2b_1 \\ a_2b_2 \\ a_2b_3
\end{pmatrix}
\end{align}

</font>
<BR>

Here is a corresponding numerical example:

<BR>
<font color="blue">
    
\begin{align}
\begin{pmatrix}
1 \\ 4
\end{pmatrix} \otimes 
\begin{pmatrix}
5 \\ 2 \\ 4
\end{pmatrix} = 
\begin{pmatrix}
1 \begin{pmatrix}
5 \\ 2 \\ 4
\end{pmatrix} \\
4 \begin{pmatrix}
5 \\ 2 \\ 4
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
5 \\ 2 \\ 4 \\ 20 \\ 8 \\ 16
\end{pmatrix}
\end{align} 

</font>
<BR>

### Here is the code for computing this tensor product:

In [9]:
ket_X = np.matrix([[1], 
                   [4]])


ket_Y = np.matrix([[5], 
                   [2], 
                   [4]])



np.kron(ket_X, ket_Y)

matrix([[ 5],
        [ 2],
        [ 4],
        [20],
        [ 8],
        [16]])

# <font color="red">Graded Exercises</font>  for use <font color="blue">with structured courses.</font>

## Tensor Products

#### <font color="blue">*This work will take some time, so block off enough time to adequately cover it*</font>. 


- Go through the **entire** JNB and complete each of the exercises, including any supplementary Video's - hand in completed <font color="red">**PDF**</font> from this JNB once finished.


- Step through the code for **each** of the above exercises, make sure you can (1) execute it, and (2) know what it does.


- <font color="blue">Complete Challenge Exercises below.</font> **(turn in the JNB)**

## Exercises: Tensor Products
- In Python.

### <font color="red">1</font>: Using the following rule: 

<BR>
<font color="blue">

\begin{align}
\begin{pmatrix}
a_1 \\ a_2 \\ a_3
\end{pmatrix} \otimes
\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} = 
\begin{pmatrix}
a_1 \begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} \\ a_2\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix} \\ a_3\begin{pmatrix}
b_1 \\ b_2
\end{pmatrix}
\end{pmatrix} = 
\begin{pmatrix}
a_1b_1 \\ a_1b_2 \\ a_2b_1 \\ a_2b_2 \\ a_3b_1 \\ a_3b_2
\end{pmatrix}
\end{align}

</font>
<BR>

> **Write Python code to compute the below computation** using the <font color="blue" size=4>**"np.kron()"**</font> function. 
- Remember to define two column (ket) vectors as matrices first.  

<BR>
<font color="blue">
    
\begin{align}
\begin{pmatrix}
2 \\ 7 \\ 3
\end{pmatrix} \otimes
\begin{pmatrix}
5 \\ 9
\end{pmatrix}
\end{align}

</font>
<BR>

In [10]:
ket_X = np.matrix([[2], 
                   [7],
                   [3]])


ket_Y = np.matrix([[5], 
                   [9]])



np.kron(ket_X, ket_Y)

matrix([[10],
        [18],
        [35],
        [63],
        [15],
        [27]])

### <font color="red">For Reference</font>: Various Spins

<BR>
    
<font color="blue">
    
\begin{align}
\text{spin-up}: \ |0\rangle &= \begin{pmatrix} 1\\0 \end{pmatrix} \\
\text{spin-down}: \ |1\rangle & = \begin{pmatrix} 0\\1 \end{pmatrix}
\end{align}

<BR>
</font>

<BR>
<font color="blue">
    
\begin{align}
\text{spin-right}: \ |r\rangle &= \begin{pmatrix} 1/\sqrt{2} \\ i/\sqrt{2} \end{pmatrix} = \frac{1}{\sqrt{2}} \left(|0\rangle + i|1\rangle\right) \\
\text{spin-left}: \ |l\rangle & = \begin{pmatrix} 1/\sqrt{2} \\ -i/\sqrt{2} \end{pmatrix} = \frac{1}{\sqrt{2}} \left(|0\rangle - i|1\rangle\right)
\end{align}

</font>

<BR><BR>
    
<font color="blue">
    
\begin{align}
\text{spin +}: \ |+\rangle &= \begin{pmatrix} 1/\sqrt{2} \\ 1/\sqrt{2} \end{pmatrix} = \frac{1}{\sqrt{2}} \left(|0\rangle + |1\rangle\right) \\
\text{spin -}: \ |-\rangle & = \begin{pmatrix} 1/\sqrt{2} \\ -1/\sqrt{2} \end{pmatrix} = \frac{1}{\sqrt{2}} \left(|0\rangle - |1\rangle\right)
\end{align}

</font>

<BR>

### <font color="red">For Reference</font>: Basis States


> - **Tensor products of the basis states <font color="red">$|0\rangle$</font> and <font color="red">$|1\rangle$</font>**. 


<BR>
<font color="blue">

\begin{align}
|00 \rangle &= |0\rangle \otimes |0\rangle = \begin{pmatrix} 1\\0 \end{pmatrix} \otimes \begin{pmatrix} 1\\0 \end{pmatrix} = \begin{pmatrix} 1\\0\\0\\0 \end{pmatrix} \\
|01 \rangle &= |0\rangle \otimes |1\rangle = \begin{pmatrix} 1\\0 \end{pmatrix} \otimes \begin{pmatrix} 0\\1 \end{pmatrix} = \begin{pmatrix} 0\\1\\0\\0 \end{pmatrix} \\
|10 \rangle &= |1\rangle \otimes |0\rangle = \begin{pmatrix} 0\\1 \end{pmatrix} \otimes \begin{pmatrix} 1\\0 \end{pmatrix} = \begin{pmatrix} 0\\0\\1\\0 \end{pmatrix} \\
|11 \rangle &= |1\rangle \otimes |1\rangle = \begin{pmatrix} 0\\1 \end{pmatrix} \otimes \begin{pmatrix} 0\\1 \end{pmatrix} = \begin{pmatrix} 0\\0\\0\\1 \end{pmatrix}
\end{align}

</font>

<BR>

### <font color="red">For Reference</font>: Python for Various Spins

In [11]:
# SPIN-UP
spin_up = np.matrix([[1], [0]])

# SPIN-DOWN
spin_down = np.matrix([[0], [1]])

# SPIN-RIGHT
spin_right = (1/np.sqrt(2))*(spin_up + 1j*spin_down)

# SPIN-LEFT
spin_left = (1/np.sqrt(2))*(spin_up - 1j*spin_down)

# SPIN-PLUS
spin_plus = (1/np.sqrt(2))*(spin_up + spin_down)

# SPIN-MINUS
spin_minus = (1/np.sqrt(2))*(spin_up - spin_down)


print('spin up:', spin_up, "\n")
print('spin down:', spin_down, "\n")
print('spin right:', spin_right, "\n")
print('spin left:', spin_left, "\n")
print('spin plus:', spin_plus, "\n")
print('spin minus:', spin_minus, "\n")

spin up: [[1]
 [0]] 

spin down: [[0]
 [1]] 

spin right: [[0.70710678+0.j        ]
 [0.        +0.70710678j]] 

spin left: [[0.70710678+0.j        ]
 [0.        -0.70710678j]] 

spin plus: [[0.70710678]
 [0.70710678]] 

spin minus: [[ 0.70710678]
 [-0.70710678]] 



### <font color="red">2</font>: Write Python code to compute $|0\rangle \otimes |0 \rangle $. 
- Spin-UP / Spin-UP

### <font color="red">This first one is done for you</font>.

In [12]:
np.kron(spin_up, spin_up)

matrix([[1],
        [0],
        [0],
        [0]])

### <font color="red">3</font>: Write Python code to compute $|0\rangle \otimes |1 \rangle $. 
- Spin-UP / Spin-DOWN

In [13]:
np.kron(spin_up, spin_down)

matrix([[0],
        [1],
        [0],
        [0]])

### <font color="red">4</font>: Write Python code to compute $|1\rangle \otimes |0 \rangle $.
- Spin-DOWN / Spin-UP

In [14]:
np.kron(spin_down, spin_up)

matrix([[0],
        [0],
        [1],
        [0]])

### <font color="red">5</font>: Write Python code to compute $|1\rangle \otimes |1 \rangle $.
- Spin-DOWN / Spin-DOWN

In [15]:
np.kron(spin_down, spin_down)

matrix([[0],
        [0],
        [0],
        [1]])

### <font color="red">6</font>: Write Python code to compute $|l\rangle \otimes |r \rangle $.
- Spin-LEFT / Spin-RIGHT

In [16]:
np.kron(spin_left, spin_right)

matrix([[0.5+0.j ],
        [0. +0.5j],
        [0. -0.5j],
        [0.5+0.j ]])

### <font color="red">7</font>: Write Python code to compute $|+\rangle \otimes |- \rangle $.
- Spin-PLUS / Spin-MINUS

In [17]:
np.kron(spin_plus, spin_minus)

matrix([[ 0.5],
        [-0.5],
        [ 0.5],
        [-0.5]])

![the-end](img/the-end.png "the-end")