# Preparing Basis States in PennyLane


- #### Hands-on Experiential Learning <font color="red">for the Software Engineer</font>

![](img/QC_Math_Banner.png "")

<font color="red">**Notice**</font>: All materials herein were <font color="red">**curated**</font> by **Matthew R. Versaggi (profversaggi@gmail.com)** and are released into the open source to foster growth and welfare of expanding the Quantum Computing domain - the only obligation one incurs when using, copying, distributing or referencing this is to kindly reference the author and send me an email so I know how useful the material is to you.

#### <font color="red">Recommendations</font>: 

> **<font color="blue">It's highly recommended to take structured QC Math courses <font color="red">like</font>:</font>**
> #### Math Prerequisites for Quantum Computing
> - https://www.udemy.com/course/mathematics-prerequisites-for-quantum-computing-and-quantum-physics/

> #### Advanced Math for Quantum Computing
> - https://www.udemy.com/course/qc201-advanced-math-for-quantum-computing-mathematics-physics/



#### <font color="red">Materials Inspiration and Author(s)</font>: 

> **<font color="blue">Amelie Schreiber</font>**
- Article: https://towardsdatascience.com/quantum-computing-for-the-newb-5e0737e3ca4
- Course: https://the-singularity-research.github.io/linear_algebra_for_quantum_computing/
- GitHub: https://github.com/The-Singularity-Research/linear_algebra_for_quantum_computing

> **<font color="blue">QWorld</font>**
- Site: https://qworld.lu.lv/
- GitLab: https://gitlab.com/qkitchen/basics-of-quantum-computing

## Importing PennyLane and the wrapped version of NumPy

#### PennyLane is an open source software for <font color="blue">quantum machine learning</font> and <font color="blue">quantum computing algorithms</font>. 

- It integrates standard machine learning software and tools, such as TensorFlow and Pytorch, with quantum computing software like IBM's Qiskit, Microsoft's Q#, and Google's Cirq. 

- It also has its own built in functions and models, and allows various hardware backends such as the quantum computers available from IBM via free cloud access. 

- PennyLane has a **wrapped version of NumPy** that we import rather than the standard NumPy we have been using. 

In [4]:
# pip install pennylane

In [1]:
import pennylane as qml
from pennylane import numpy as np

### <font color="red">**Why this is important**</font>: 

## <font color="blue">Basis States</font>


#### In PennyLane, and other quantum computing software, we often want to prepare basis states. 

This is something we will return to again in the future when we study specific cases of quantum circuits, but having some basic introduction to state preparation now seems appropriate since **they are simply tensor products of the basis states <font color="blue">UP</font>: <font color="red">$|0\rangle$</font> and <font color="blue">DOWN</font>: <font color="red">$|1\rangle$</font>**. 

> In particular, we can prepare states like

<BR>
<font color="blue">

\begin{align}
|00 \rangle &= |0\rangle \otimes |0\rangle = \begin{pmatrix} 1\\0 \end{pmatrix} \otimes \begin{pmatrix} 1\\0 \end{pmatrix} = \begin{pmatrix} 1\\0\\0\\0 \end{pmatrix} \\
|01 \rangle &= |0\rangle \otimes |1\rangle = \begin{pmatrix} 1\\0 \end{pmatrix} \otimes \begin{pmatrix} 0\\1 \end{pmatrix} = \begin{pmatrix} 0\\1\\0\\0 \end{pmatrix} \\
|10 \rangle &= |1\rangle \otimes |0\rangle = \begin{pmatrix} 0\\1 \end{pmatrix} \otimes \begin{pmatrix} 1\\0 \end{pmatrix} = \begin{pmatrix} 0\\0\\1\\0 \end{pmatrix} \\
|11 \rangle &= |1\rangle \otimes |1\rangle = \begin{pmatrix} 0\\1 \end{pmatrix} \otimes \begin{pmatrix} 0\\1 \end{pmatrix} = \begin{pmatrix} 0\\0\\0\\1 \end{pmatrix}
\end{align}

</font>

<BR>

#### Define Spin-UP and Spin-DOWN in Python

In [2]:
# Define single qubit states spin-up and spin-down

# spin-up
u = np.matrix([[1],
               [0]])

# spin-down
d = np.matrix([[0],
               [1]])

# Define the basis states:
uu = np.kron(u, u)
ud = np.kron(u, d)
du = np.kron(d, u)
dd = np.kron(d, d)

#### UP / UP

In [3]:
print('|00> =')
print(uu)

|00> =
[[1]
 [0]
 [0]
 [0]]


#### UP / DOWN

In [4]:
print('|01> =')
print(ud)

|01> =
[[0]
 [1]
 [0]
 [0]]


#### DOWN / UP

In [5]:
print('|10> =')
print(du)

|10> =
[[0]
 [0]
 [1]
 [0]]


#### DOWN / DOWN

In [6]:
print('|11> =')
print(dd)

|11> =
[[0]
 [0]
 [0]
 [1]]


### Maturing this <font color="red">further</font>, we can define states like:
<BR>
<font color="blue">
    
\begin{align}
|000\rangle = |0\rangle \otimes |0\rangle \otimes |0\rangle = \begin{pmatrix} 1\\0\\0\\0\\0\\0\\0\\0 \end{pmatrix}
\end{align}

\begin{align}
|010\rangle = |0\rangle \otimes |1\rangle \otimes |0\rangle = \begin{pmatrix} 0\\0\\1\\0\\0\\0\\0\\0 \end{pmatrix}
\end{align}

</font>

<BR>

### In PennyLane the following code defines a device (quantum computer or simulator) on which to run code. 

- We will use the **default simulator** for now since the code is very simple and running it on an actual quantum computer is unnecessary. 

- The **number of wires is equal to the number of qubits** we are using. 

- The number of **shots is the number of times** we want to run the circuit.

In [7]:
dev = qml.device("default.qubit", wires=2, shots=1)

#### Now we can define an array that corresponds to the basis state UP : UP  - <font color="red">$|00\rangle$</font>:

In [8]:
uu = np.array([0, 0])

####  We can define a function `circuit()` that defines a quantum (<font color="red">Pauli_Z</font>) circuit. 

---
## ( <font color="red">Z</font> )

<BR>
<font color="blue" size=4>
    
$$
\begin{bmatrix} 
1 & 0\\ 
0 & -1
\end{bmatrix}
$$

</font>
<BR>
    
    
The effect of this gate leaves a qubit's |0$\rangle$ amplitude unchanged, while multiplying by -1 (phase) to a qubit's |1$\rangle$ amplitude.  The power of this gate comes from the fact that it only affects the |$1\rangle$ component, which will be frequently used for picking out certain states in the system while leaving others unaltered.

<BR><BR>

In [9]:
def circuit():
    qml.BasisState(uu, wires=[0, 1])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1))

#### Now, we define a `qnode` class that <font color="red">runs</font> on the device we have defined and samples the qubits and gives a $+1$ for spin-up and a $-1$ for spin down. 

> This runs a quantum function (circuit) that we have just defined. 

In [10]:
@qml.qnode(dev)
def circuit():
    qml.BasisState(uu, wires=[0, 1])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1))

print(circuit())

[[1]
 [1]]


#### Since qubits are by default in the spin-up state for any quantum circuit, and since we did not prepare any special initial state or perform any operations on the qubits, we get an expectation value of $+1$ for both when sampling the circuit. 
- <font color="red">NOTE</font>: The vector above show a $+1$ in the first and second entry <font color="blue">meaning it is measuring two spin-up states</font>. 
> - UP : UP  <font color="red">$|00\rangle$</font>:


> #### Let's define a new state to prepare corresponding to UP : DOWN  - <font color="red">$|01 \rangle$</font>:

In [11]:
ud = np.array([0,1])

Next, let's define a new `qnode` to sample corresponding to this prepared state:

In [12]:
@qml.qnode(dev)
def circuit():
    qml.BasisState(ud, wires=[0, 1])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1))

print(circuit())

[[ 1]
 [-1]]


#### As we can see, we get a $+1$ in the first component, corresponding to the spin-up state, and we get a $-1$ in the second component corresponding to the spin-down state. 

- We can also tell PennyLane to perform **multiple "shots" or samples** by defining a new device:

In [13]:
dev2 = qml.device("default.qubit", wires=2, shots=10)

In [14]:
@qml.qnode(dev2)
def circuit():
    qml.BasisState(ud, wires=[0, 1])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1))

print(circuit())

[[ 1  1  1  1  1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]


This gives us **10 output samples** instead of just one. 

- If we define a new array corresponding to the state $|11\rangle$,

In [15]:
dd = np.array([1,1])

We can define a new **'qnode'** with the new device we just defined, and we should expect an output vector of 

<BR>
<font color="blue">
    
\begin{align}
\begin{pmatrix}
-1\\-1
\end{pmatrix}
\end{align}

</font>
<BR>

**ten times**, corresponding to the **ten samples**:

In [16]:
@qml.qnode(dev2)
def circuit():
    qml.BasisState(dd, wires=[0, 1])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1))

print(circuit())

[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]


We will return to this when we discuss **measurements** and **expectation** values. 

# <font color="red">Graded Exercises</font>  for use <font color="blue">with structured courses.</font>

## Preparing Basis States

#### <font color="blue">*This work will take some time, so block off enough time to adequately cover it*</font>. 


- Go through the **entire** JNB and complete each of the exercises, including any supplementary Video's - hand in completed <font color="red">**PDF**</font> from this JNB once finished.


- Step through the code for **each** of the above exercises, make sure you can (1) execute it, and (2) know what it does.


- <font color="blue">Complete Challenge Exercises below.</font> **(turn in the JNB)**

## Exercises: Preparing Basis States

### Write (Python/ Pennylane) code to compute the following basis states  (1- 8 below):

<BR>
<font color="blue">
    
1. $|000 \rangle$
2. $|001 \rangle$
3. $|010 \rangle$
4. $|011 \rangle$
5. $|100 \rangle$
6. $|101 \rangle$
7. $|110 \rangle$
8. $|111 \rangle$

</font>
<BR>
    
    

### <font color="red">Optional</font>: Compute these by hand (<font color="blue">don't hand in</font>) to spot check that your code is working correctly. 

> **For example**: the first computation will be

\begin{align}
\begin{pmatrix} 1\\0 \end{pmatrix} \otimes
\begin{pmatrix} 1\\0 \end{pmatrix} \otimes
\begin{pmatrix} 0\\1 \end{pmatrix}
\end{align}

### <font color="red">1</font>: $|000 \rangle$

### <font color="red">This first one is done for you</font>.

<BR>
<font color="blue">
    
\begin{align}
|000\rangle = |0\rangle \otimes |0\rangle \otimes |0\rangle = \begin{pmatrix} 1\\0\\0\\0\\0\\0\\0\\0 \end{pmatrix}
\end{align}

</font>

<BR>

> - **(a):** Define a **Quantum Device**

In [18]:
dev_pbm_1 = qml.device("default.qubit", wires=3, shots=1)
dev_pbm_1

<DefaultQubit device (wires=3, shots=1) at 0x7f9988b59430>

> - **(b):** Define an array that corresponds to the basis state (**uuu**) <font color="red">$|000\rangle$</font>:


In [19]:
uuu = np.array([0, 0, 0])
uuu

tensor([0, 0, 0], requires_grad=True)

> - **(c):** Define the **function** **`circuit()`** that defines a quantum (**<font color="red">Pauli_Z</font>**) circuit. 

In [20]:
def circuit():
    qml.BasisState(uuu, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

> - **(d):** **Define** and **Run** a **`qnode`** class that **<font color="red">runs</font>** on the device we have defined and samples the qubits and gives a **<font color="blue">($+1$) for spin-up</font>** and a **<font color="blue">($-1$) for spin down</font>**. 
>> -  **Analyse** the results. 


In [21]:
@qml.qnode(dev_pbm_1)
def circuit():
    qml.BasisState(uuu, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

print("\n Circuit Run Results: \n\n", circuit())


 Circuit Run Results: 

 [[1]
 [1]
 [1]]


#### **<font color="red">ANALYSIS</font>**: 

> Since qubits are by default in the spin-up state for <font color="red">any</font> quantum circuit, and since we did not prepare any special initial state or perform any operations on the qubits, **we get an expectation value of ($+1$) when sampling the circuit**. 

- The vector above show a $+1$ in the **first, second,** and **third** entry <font color="blue">meaning it is measuring</font> <font color="red">**three**</font> **Spin-UP** states. 

### <font color="red">2</font>: $|001 \rangle$

In [24]:
uud = np.array([0, 0, 1])
uud

def circuit():
    qml.BasisState(uud, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

@qml.qnode(dev_pbm_1)
def circuit():
    qml.BasisState(uud, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

print("\n Circuit Run Results: \n\n", circuit())


 Circuit Run Results: 

 [[ 1]
 [ 1]
 [-1]]


### <font color="red">3</font>: $|010 \rangle$

In [26]:
udu = np.array([0, 1, 0])
udu

def circuit():
    qml.BasisState(udu, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

@qml.qnode(dev_pbm_1)
def circuit():
    qml.BasisState(udu, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

print("\n Circuit Run Results: \n\n", circuit())


 Circuit Run Results: 

 [[ 1]
 [-1]
 [ 1]]


### <font color="red">4</font>: $|011 \rangle$

In [28]:
udd = np.array([0, 1, 1])
udd

def circuit():
    qml.BasisState(udd, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

@qml.qnode(dev_pbm_1)
def circuit():
    qml.BasisState(udd, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

print("\n Circuit Run Results: \n\n", circuit())


 Circuit Run Results: 

 [[ 1]
 [-1]
 [-1]]


### <font color="red">5</font>: $|100 \rangle$

In [30]:
duu = np.array([1, 0, 0])
duu

def circuit():
    qml.BasisState(duu, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

@qml.qnode(dev_pbm_1)
def circuit():
    qml.BasisState(duu, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

print("\n Circuit Run Results: \n\n", circuit())


 Circuit Run Results: 

 [[-1]
 [ 1]
 [ 1]]


### <font color="red">6</font>: $|101 \rangle$

In [31]:
dud = np.array([1, 0, 1])
dud

def circuit():
    qml.BasisState(dud, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

@qml.qnode(dev_pbm_1)
def circuit():
    qml.BasisState(dud, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

print("\n Circuit Run Results: \n\n", circuit())


 Circuit Run Results: 

 [[-1]
 [ 1]
 [-1]]


### <font color="red">7</font>: $|110 \rangle$

In [32]:
ddu = np.array([1, 1, 0])
ddu

def circuit():
    qml.BasisState(ddu, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

@qml.qnode(dev_pbm_1)
def circuit():
    qml.BasisState(ddu, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

print("\n Circuit Run Results: \n\n", circuit())


 Circuit Run Results: 

 [[-1]
 [-1]
 [ 1]]


### <font color="red">8</font>: $|111 \rangle$

In [33]:
ddd = np.array([1, 1, 1])
ddd

def circuit():
    qml.BasisState(ddd, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

@qml.qnode(dev_pbm_1)
def circuit():
    qml.BasisState(ddd, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

print("\n Circuit Run Results: \n\n", circuit())


 Circuit Run Results: 

 [[-1]
 [-1]
 [-1]]


### <font color="red">9</font>: Define a default device with <font color="red">"3 wires"</font> and <font color="red">"5 shots"</font>.

In [34]:
dev_pbm_2 = qml.device("default.qubit", wires=3, shots=5)
dev_pbm_2

<DefaultQubit device (wires=3, shots=5) at 0x7f99612f1d90>

### <font color="red">10</font>: Define an array <font color="red">'uud'</font> for the basis state <font color="red">$|001\rangle$</font>.

In [35]:
uud = np.array([0, 0, 1])
uud

tensor([0, 0, 1], requires_grad=True)

### <font color="red">11</font>: Define a <font color="red">qnode</font> that will print the samples: 

> `qml.sample(qml.PauliZ(0))`

> `qml.sample(qml.PauliZ(1))` 

> `qml.sample(qml.PauliZ(2))`

In [36]:
def circuit():
    qml.BasisState(uud, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

### <font color="red">12</font>:  Run your <font color="red">qnode</font> and verify that you get the output vector

<BR>
<font color="blue">
\begin{align}
\begin{pmatrix}
1 \\ 1 \\ -1
\end{pmatrix}
\end{align}
    
</font>
<BR>

### five times.

In [37]:
@qml.qnode(dev_pbm_2)
def circuit():
    qml.BasisState(uud, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

print("\n Circuit Run Results: \n\n", circuit())


 Circuit Run Results: 

 [[ 1  1  1  1  1]
 [ 1  1  1  1  1]
 [-1 -1 -1 -1 -1]]


### <font color="red">13</font>: <font color="red">OPTIONAL</font> - Try doing this with the other basis states given in <font color="blue">Exercises 1-8</font>.

In [38]:
dev_pbm_3 = qml.device("default.qubit", wires=3, shots=10)
dev_pbm_3

dud = np.array([1, 0, 1])
dud

def circuit():
    qml.BasisState(dud, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

@qml.qnode(dev_pbm_3)
def circuit():
    qml.BasisState(dud, wires=[0, 1, 2])
    return qml.sample(qml.PauliZ(0)), qml.sample(qml.PauliZ(1)), qml.sample(qml.PauliZ(2))

print("\n Circuit Run Results: \n\n", circuit())


 Circuit Run Results: 

 [[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [ 1  1  1  1  1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]


![the-end](img/the-end.png "the-end")